# Generated by Django 4.1.6 on 2023-02-16 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_chatroom_message_chat_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='user_1',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='user_2',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to=settings.AUTH_USER_MODEL),
        ),
    ]
