# Generated by Django 4.1.7 on 2023-03-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_profilesummary_tutorprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='experience',
            field=models.IntegerField(default=3),
        ),
    ]
