# Generated by Django 4.1.5 on 2023-01-31 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_subjectandlevels_remove_subject_user_delete_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectandlevels',
            old_name='user',
            new_name='users',
        ),
    ]
