# Generated by Django 4.1.7 on 2023-03-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tutorprofile_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='experience',
            field=models.IntegerField(),
        ),
    ]
