# Generated by Django 4.1.7 on 2023-03-04 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_tutorprofile_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorprofile',
            old_name='experience',
            new_name='initial_experience',
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 4, 14, 39, 36, 695376), editable=False),
        ),
    ]
