# Generated by Django 4.1.7 on 2023-03-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_experience_tutorprofile_initial_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
