# Generated by Django 4.1.7 on 2023-03-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_tutorprofile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='education',
            field=models.CharField(default='Harvard', max_length=255),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='occupation',
            field=models.CharField(default='Secondary School Teacher', max_length=255),
        ),
    ]
