# Generated by Django 4.1.5 on 2023-02-06 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_bookedslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedslot',
            name='subject_and_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subjectandlevel'),
        ),
    ]
