# Generated by Django 4.1.5 on 2023-02-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_bookedslot_subject_and_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedslot',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], max_length=10, null=True),
        ),
    ]
