# Generated by Django 4.1.7 on 2023-03-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_tutorprofile_education_tutorprofile_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='education',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='occupation',
            field=models.CharField(max_length=255),
        ),
    ]
