# Generated by Django 4.1.5 on 2023-02-07 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_bookedslot_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedslot',
            old_name='students',
            new_name='student',
        ),
    ]
