# Generated by Django 4.1.7 on 2023-03-28 11:24

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_subjectandlevel_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='profile_picture',
            field=models.ImageField(default='images/profile_pictures/default.jpg', upload_to=main.models.upload_path),
        ),
    ]
