# Generated by Django 4.1.7 on 2023-02-26 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.level')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subjects', models.ManyToManyField(to='main.subject')),
            ],
        ),
        migrations.CreateModel(
            name='BookedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], max_length=10)),
                ('day_and_time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.dayandtime')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent.student')),
                ('subject_and_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subjectandlevel')),
            ],
        ),
    ]
