# Generated by Django 4.1.5 on 2023-02-05 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parent', '0002_subject_delete_subjectandlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
